<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>WFO1000</NoWarn>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program_V13.cs" />
    <Compile Remove="Program_V14.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Core" Version="2.*" />
    <PackageReference Include="OxyPlot.WindowsForms" Version="2.*" />
  </ItemGroup>

</Project>